name:                aoc2023
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/alexjercan/aoc2023#readme
license:             BSD-3-Clause
author:              Alex Jercan
maintainer:          alex_jercan27@yahoo.com
copyright:           2023 Alex Jercan
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - split
  - parsec
  - containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  day01:
    source-dirs:     src
    main:            Day01
    other-modules:   []

  day02:
    source-dirs:     src
    main:            Day02
    other-modules:   [Util.Parser]

  day03:
    source-dirs:     src
    main:            Day03
    other-modules:   []

  day04:
    source-dirs:     src
    main:            Day04
    other-modules:   [Util.Parser]

  day05:
    source-dirs:     src
    main:            Day05
    other-modules:   []

  day06:
    source-dirs:     src
    main:            Day06
    other-modules:   []

  day07:
    source-dirs:     src
    main:            Day07
    other-modules:   []

  day08:
    source-dirs:     src
    main:            Day08
    other-modules:   []

  day09:
    source-dirs:     src
    main:            Day09
    other-modules:   []

  day10:
    source-dirs:     src
    main:            Day10
    other-modules:   []

  day11:
    source-dirs:     src
    main:            Day11
    other-modules:   []

  day12:
    source-dirs:     src
    main:            Day12
    other-modules:   []

  day13:
    source-dirs:     src
    main:            Day13
    other-modules:   []

  day14:
    source-dirs:     src
    main:            Day14
    other-modules:   []

  day15:
    source-dirs:     src
    main:            Day15
    other-modules:   []

  day16:
    source-dirs:     src
    main:            Day16
    other-modules:   []

  day17:
    source-dirs:     src
    main:            Day17
    other-modules:   []

  day18:
    source-dirs:     src
    main:            Day18
    other-modules:   []

  day19:
    source-dirs:     src
    main:            Day19
    other-modules:   []

  day20:
    source-dirs:     src
    main:            Day20
    other-modules:   []

  day21:
    source-dirs:     src
    main:            Day21
    other-modules:   []

  day22:
    source-dirs:     src
    main:            Day22
    other-modules:   []

  day23:
    source-dirs:     src
    main:            Day23
    other-modules:   []

  day24:
    source-dirs:     src
    main:            Day24
    other-modules:   []

  day25:
    source-dirs:     src
    main:            Day25
    other-modules:   []

tests:
  spec:
    main: Main.hs
    source-dirs:
      - src
      - test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - hspec
